name: Eleventy Build
on: [push]
jobs:
  build_deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: TartanLlama/actions-eleventy@v1.3
      - name: CNAME
        run: echo 'sybrand.ink' | sudo tee _site/CNAME
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.1
        env:
          PUBLISH_DIR: _site 
          PUBLISH_BRANCH: gh-pages
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
